test/hackney_integration_tests.erl
=> Add HEAD request test

src/hackney_client/hackney.erl, src/hackney_client/hackney_stream.erl, test/hackney_integration_tests.erl
It fixes the problem with 304 and 204 responses that don't provide `Content-Lenght` header (e.g. google API).
Reading of body halts until `{error {closed, <<>>}}` after a long timeout.
The returning tuple for this response changes to `{ok, Status, Headers}`, same as for HEAD requests 7b60ae08 (let me know if you'd like to keep current `{ok, Status, Headers, Ref}` behaviour).
The httpbin has no way not to provide `Content-Lenght` thus I'm looking for another way to test the lack of `Content-Lenght`, that I think will be an another PR.
Relates to #118. \cc @edgurgel
=> Fix handling of bodiless (204, 304 codes) responses

src/hackney_client/hackney_stream.erl
Same fix as benoitc/hackney#152
=> Handle HTTP/1.1 when async streaming

rebar.config, rebar_dev.config
=> use ssl_verify_hostname from deadtrickster

src/hackney_client/hackney.erl
Corrected "methos" to "method".
=> Correct typo in hackney.erl

include/hackney.hrl, src/hackney_client/hackney.erl, src/hackney_connect/hackney_connect.erl
Sets maximum allowed size of the body if `with_body` is true.
=> add max_body option

src/hackney_client/hackney.erl
- Don't override `Host` header
- Merge redirect url with current path
=> fix redirect to relative url

rebar.config.script
=> Remove cowboy from list of default rebar2 deps

src/hackney_sup.erl
Generally found this to be a good idea for top level app supervisors,
especially as part of proper releases.
=> Increase hackney_sup supervisor restart tolerance

mix.exs
=> Define application module in mix packaging

src/hackney.erl
Implements https://github.com/benoitc/hackney/issues/229
=> Allow force non-POST 303 redirects

src/hackney_response.erl
We should always close sockets to avoid leak.
=> Close socket on errors

src/hackney_http_connect.erl
This code didn't work for me without these changes
=> Bug fix for bad header format and allow IPv6

src/hackney.erl
Trailing whitespaces are also removed by my editor.
=> Fix various typo in hackney.erl

src/hackney_request.erl
hacknet_headers_new => hackney_headers_new
=> fixed undefined function

src/hackney_manager.erl
#411 sockets remain in CLOSE-WAIT state in async mode through proxy without connection pool
=> #411 sockets remain in CLOSE-WAIT

README.md, test/hackney_integration_tests.erl
I added two tests, one of which would have caught the manager leak in #445.
=> Added unit tests for reference leaks

rebar.config, src/hackney_http_connect.erl
I was unable to test this on R16B03-1. It should work though. Fixes https://github.com/benoitc/hackney/issues/449
=> Send SNI for erlang >= 17

src/hackney_socks5.erl
Fix bad_request error when SOCKS5 proxy replied with domain name
=> Fix error with incorrect domain handling in SOCKS5 response

src/hackney_pool.erl
Fixes https://github.com/benoitc/hackney/issues/452 ....probably.
=> fix return value of del_from_queue

rebar.config, rebar.config.script, rebar.lock
=> chore(idna): Upgrade to version 5.1.1

src/hackney_socks5.erl
=> Fix SOCKS5 IPv4 and IPv6 argument error

src/hackney_socks5.erl
make a same fix as #455 to the SOCKS5 proxy.
=> Send SNI when SOCKS5 proxying

include/hackney.hrl, include/hackney_lib.hrl, src/hackney.erl, src/hackney_http.erl, src/hackney_response.erl, src/hackney_stream.erl, src/hackney_util.erl, test/empty_clen_resource.erl, test/hackney_multipart_tests.erl, test/hackney_noclen_tests.erl
when the connection is closed but buffer not empty, return and OK
result.
fix #475
=> fix return for empty content length

src/hackney_url.erl
=> don't encode host for unix scheme

README.md, doc/README.md, doc/hackney_multipart.md, doc/overview.edoc, src/hackney_multipart.erl, src/hackney_request.erl
Sending form with a field names for files
=> multipart: DOM element name definition for files

doc/hackney.md, src/hackney.erl
Hi, I noticed a grammatical error and fixed it. :)
=> Fix misspelling

README.md, doc/README.md, doc/overview.edoc
Also document how to use client certificates, and CRLs.
=> document self-signed certificate usage

src/hackney_tcp.erl
:)
http://i.imgur.com/vOWAAUK.png
=> Use spaces

src/hackney_http.erl, test/hackney_http_tests.erl
Split from https://github.com/benoitc/hackney/pull/604:
In this PR the last CRLF in chunked responses is parsed to avoid
having garbage in front of the next response in the connection. This garbage could be CRLF or simply LF, depending on what did the binary received by the socket contain.
=> Handle trailers in persistent connections

src/hackney_pool.erl
Hi,
Some time back I made a fix #652 for issue #651
The fix itself is fine, but it seems like we made a hurried decision to add a protective timeout for waiting checkout results https://github.com/benoitc/hackney/pull/652/commits/23d44cbbd42da2f4ddcd49466ece8cbff3285937
The problem is that there are two timers involved in the pool checkout procedure `ConnectTimeout` and `CheckoutTimeout`
Therefore we should wait at least `ConnectTimeout + CheckoutTimeout` to let the intermediary process to complete
However, even doing that we might end up sending unexpected ({checkout,#Ref<...>,{error,checkout_timeout}}) messages to the application process because of having more than one guard timer for the same purpose armed for the same timeout
To be absolutely sure we have to  `ConnectTimeout + …
=> Fix race condition within pool checkout procedure

src/hackney.erl, src/hackney_stream.erl
Fixes #635 
I'm not sure if I need to make other changes. Did a few searches on the codebase and did not find obvious things to change. Let me know if I missed something.
=> Follow HTTP 308 redirects

include/hackney.hrl, src/hackney.erl
just like curl and other tools allows hackney to retrieve HTTP  proxy informations from environnment:
=> get proxy info from environnment

src/hackney_response.erl
ensure we can still receive the trailers when not on stream and body_state is done and the parser state is on_trailers
=> recev stream: fix case when body_state=done

src/hackney_http.erl
for #695 
Any response code < 200 shall be ignored, together with whatever header lines there are.
=> add junk line skipping for 1XX responses

src/hackney_happy.erl, src/hackney_ssl.erl
* fix ssl options
* fix timeout
=> Fix happy eyeball
