src/hackney_client/hackney.erl
test/hackney_integration_tests.erl

Make bodiless responses consistent with the rest of API

---

src/hackney_client/hackney_response.erl

According to http://www.w3.org/Protocols/rfc1341/4_Content-Type.html,
"The type, subtype, and parameter names are not case sensitive. For
example, TEXT, Text, and TeXt are all equivalent. Parameter values are
normally case sensitive"
It is very important to make multipart parser works since multipart
boundary are often with uppercase characters. Currently this makes
the multipart parser fail most of the time.
It is OK to just remove the to_lower, since hackney_headers:content_type
uses hackney_bstr:token_ci (case insensitive) to parse the type and
subtype returning the wanted type and subtype as lowercase and params
with case.

CT params are case sensitive, remove to_lower

---

src/hackney_connect/hackney_http_connect.erl
src/hackney_connect/hackney_socks5.erl

The removal of inclusion of this file saves us dependency on erlang-src.

Stop including an unused file.

---

src/hackney_lib/hackney_http.erl

a `<<"\r\b">>` at the beginning of the buffer passed to `parse_headers/1` prevented parser from correctly parsing headers. It is correctly deleted when handling responses. (see line 194 of `src/hackney_lib/hackney_http.erl`)

removing extra CRLF at the start of buffer before passing it to `parse_headers`

---

src/hackney_client/hackney_stream.erl

This fixes a bug where `done` is not sent causing the request to never complete for the receiver.

Always send done when async streaming

---

src/hackney_lib/hackney_http.erl
test/hackney_http_tests.erl

Status line parsing crashes if the reason phrase is missing. This can be tested with the following request to http://mediafire.com.
```erlang
hackney:request(head, <<"http://mediafire.com/">>, [], <<"">>, []).
** exception error: no function clause matching hackney_http:parse_status(<<>>,
{hparser,response,4096,10,0,on_first_line,
<<"Date: Sun, 31 May 2015 16:54:47 GMT\r\nContent-Type: text/html; charset=utf-8\r\nCon"...>>,
undefined,undefined,[],undefined,undefined,undefined,
undefined,undefined,waiting},
{1,1},
<<"301">>) (src/hackney_lib/hackney_http.erl, line 209)
in function  hackney_response:wait_status/1 (src/hackney_client/hackney_response.erl, line 74)
in call from hackney:send_request/2 (src/hackney_client/hackney.erl, line 357)
```
This pull request contains a proposed fix as …

Fixed status line parsing when reason phrase is missing entirely.

---

src/hackney_client/hackney_request.erl

Not a bug but we only need the size of binaries, not binaries and tuples.  Also removed a redundant call to `iolist_to_binary`

Use erlang:byte_size/1 for size of binaries

---

src/hackney_connect/hackney_connect.erl

Export hackney_connect:ssl_opts/2 to fix #211 issues:
```
Warning: hackney_http_connect:connect/4 calls undefined function hackney_connect:ssl_opts/2 (Xref)
Warning: hackney_socks5:connect/4 calls undefined function hackney_connect:ssl_opts/2 (Xref)
```

Export hackney_connect:ssl_opts/2

---

src/hackney_client/hackney.erl

This typo appeared in two places in src/hackney_client/hackney.erl, and does not
seem to be related to anything except themselves.

Fix typo: ssl_opttions -> ssl_options

---

src/hackney_connect/hackney_socks5.erl

rfc for socks5 allows response [X 0] no authorization required

socks5 auth & deaf servers

---

src/hackney_connect/hackney_pool.erl

fix #230
`inet:peername/1` returns `{error, enotconnect}` against half-closed sockets.  so they should be closed here.
we make millions of http requests per minute and get few socket leak. It is very rare case and hard to reproduce. 
but when someone checkin a socket to the pool, e.g. it means " I release the ownership of it. I will never read, write and CLOSE it." , so it is sane for hackney_pool to close the half-closed socket here.

close half-closed socket to avoid leak

---

src/hackney_client/hackney.erl

It fixes this problem:
```
hackney:request(get, <<"http://rdrct.herokuapp.com/1">>, [], [], [{follow_redirect, true}, {with_body, true}]).
** exception error: {badrecord,client}
in function  hackney:redirect/2 (src/hackney_client/hackney.erl, line 864)
in call from hackney:maybe_redirect1/3 (src/hackney_client/hackney.erl, line 761)
in call from hackney:send_request/2 (src/hackney_client/hackney.erl, line 367)
in call from hackney:redirect/2 (src/hackney_client/hackney.erl, line 832)
in call from hackney:maybe_redirect1/3 (src/hackney_client/hackney.erl, line 761)
in call from hackney:send_request/2 (src/hackney_client/hackney.erl, line 367)
```
I also changed 
```
Error -> Error
```
case to
```
Response -> Response
```
because it looks more correct.

Fix redirection with enabled 'with_body' option

---

src/http/hackney_multipart.erl

Is this a bug?
http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2

fix default name value of mp file header

---

.travis.yml
rebar.config
rebar.config.script
src/http/hackney_multipart.erl
test/hackney_integration_tests.erl
test/hackney_multipart_tests.erl
test/upload_resource.erl

This PR introduces a small test case for the multipart upload. Currently it fails with a 500 error inside cowboy because hackney is doing things which is against the RFC. The PR is part of fixing #197 since it provides the counter-example for the current operation.
I envision we can take this PR and a fix together so we can avoid regressions on this area later on.

Use cowboy to test multipart/form-data

---

src/hackney.erl

We had some problems with the use of hackney in combination with dialyzer since the request methods had varying type signatures for the url.

Changed typing of request to allow a url of the type url(), binary() and list()

---

src/http/hackney_url.erl
test/hackney_url_tests.erl

In Chromium's [kPathCharLookup][1] table, the commercial at symbol is
given the flag to pass through without being escaped. This is due to
some web services using this character as a delimiter without first unescaping.
[1]: https://src.chromium.org/viewvc/chrome/trunk/src/url/url_canon_path.cc?pathrev=265120#l60

fix(hackney_url): pass "@" unescaped

---

src/hackney.erl
src/hackney_url.erl

from https://github.com/benoitc/hackney/issues/272

hackney_url:normalize function should actually use the function in the argument instead of pathencode()

---

mix.exs

Use parenthesis to remove the ambiguity with variables.

Fix Elixir 1.4 warnings

---

src/hackney_multipart.erl
src/hackney_pool.erl

These two warnings should no longer appear:
```
src/hackney_pool.erl:213: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/hackney_multipart.erl:271: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
```

Remove warnings

---

src/hackney.erl
src/hackney_socks5.erl

`Options = [{proxy, {socks5, ProxyHost, ProxyPort}}, {socks5_resolve, local}]`

force local or remote resolver for socks5 proxy (remote by default)

---

mix.exs

All the docs say that the current version is 1.6.1  Make this match what is on hex.pm.

Update mix version to reflect the version increment to 1.6.1

---

README.md
doc/README.md
doc/overview.edoc
src/hackney_util.erl

This updates the exometer configuration instructions in the
README to match the term that `mod_metrics` expects in order
to enable exometer metrics.
This also updates `mod_metrics` so that the module name used
when exometer metrics are enabled matches the name of the
module that is provided by the metrics library.

Close #291: Fix typos for configuring exometer metrics

---

.travis.yml
README.md
src/hackney_local_transport.erl
src/hackney_url.erl
test/hackney_integration_tests.erl
test/hackney_url_tests.erl

I've only added limited test coverage for now. If I'm on the right track and this is something you'll consider merging I'll be happy to try and add some more tests and docs.
Note that I've had to override the Host header in requests I sent to the Docker engine, because it doesn't like the default Host header built by Hackney from the `netloc` of http+unix URLs. That could potentialy be handled in `host_header/2`.

support for UDS on Erlang 19, using 'http+unix' scheme

---

src/hackney_http.erl

I was occasionally seeing errors in an Elixir project that I traced back to hackney. The most reliable way to see a failure was requesting http://www.apple.com Seems they sometimes are responding with a Content-Length value that had trailing whitespace.
This was the hackney error:
```
iex(1)> :hackney.get "http://www.apple.com"
** (ArgumentError) argument error
:erlang.list_to_integer('27515     ')
(hackney) /Users/rich/Projects/elixir/whistle/deps/hackney/src/hackney_response.erl:106: :hackney_response.wait_headers/4
(hackney) /Users/rich/Projects/elixir/whistle/deps/hackney/src/hackney.erl:368: :hackney.send_request/2
```
I added a test directly into the `hackney_http` module because `parse_header/2` is not exported. If this is not the correct approach, I'm happy to fix; I'm new to both …

prevent errors by handle trailing whitespace in header values

---

README.md

Do not include the protocol in the `Host` or it will
be considered part of the host name--this results in an
`nxdomain` error.

correct hackney:connect example

---

src/hackney_http.erl
test/hackney_http_tests.erl

[RFC2616 says](https://pretty-rfc.herokuapp.com/RFC2616#basic.rules):
> HTTP/1.1 header field values can be folded onto multiple lines if the
> continuation line begins with a space or horizontal tab. All linear
> white space, including folding, has the same semantics as SP. A
> recipient MAY replace any linear white space with a single SP before
> interpreting the field value or forwarding the message downstream.
>
> LWS            = [CRLF] 1*( SP | HT )
>
> SP             = <US-ASCII SP, space (32)>
> HT             = <US-ASCII HT, horizontal-tab (9)>
Hackney was not handling this correctly: it was stripping leading spaces
and tabs from continuation lines and then parsing them incorrectly as a
new header line.
This commit fixes that: `parse_header/1` now checks if the following
line …

Handle continuation lines in HTTP headers correctly

---

src/hackney_url.erl

A signed aws s3 url requires encoding space as %20 instead of plus
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html
```
The space character is a reserved character and must be encoded as "%20" (and not as "+"). 
```

Add optional urlencode options to qs

---

doc/hackney_multipart.md
src/hackney_multipart.erl

From `Boundart` to `Boundary`.

Fix a few documentation typos

---

src/hackney.erl

When sending the `host` header for a request to a unix domain socket
the value must be url encoded, since most such values have invalid
slash characters. (fixes #382)

Url encode host header for unix domain sockets

---

src/hackney_http_connect.erl
src/hackney_socks5.erl

steps to reproduce
start a proxy server that responds with error for any connect request.
```elixir
defmodule ProxyServer do
require Logger
def accept(port) do
{:ok, socket} = :gen_tcp.listen(port,
[:binary, packet: :line, active: true, reuseaddr: true])
Logger.info "Accepting connections on port #{port}"
loop_acceptor(socket)
end
defp loop_acceptor(socket) do
{:ok, client} = :gen_tcp.accept(socket)
spawn(fn -> write_line(client) end)
loop_acceptor(socket)
end
defp write_line(socket) do
:gen_tcp.send(socket, "HTTP/1.0 404 Not Found\r\nServer: squid/3.1.23\r\nMime-Version: 1.0\r\nDate: Sat, 04 Mar 2017 19:16:09 GMT\r\nContent-Type: text/html\r\nContent-Length: 3402\r\nX-Squid-Error: ERR_DNS_FAIL 0\r\nVary: Accept-Language\r\nContent-Language: en\r\n\r\n")
end
end
ProxyServer.accept(5000) …
```

fix connection leak

---

src/hackney_pool.erl

We were experiencing request calls that hung indefinitely due to connections not being available in the pool. Similar to issue https://github.com/benoitc/hackney/issues/391
The hackney_pool should now respect the connect_timeout setting and returns an {error, connect_timeout}
Is this a good way to handle this? Would you like me to adds some tests?

uses the connect timeout for the checkout call

---

src/hackney_manager.erl
src/hackney_stream.erl

Sometimes {active,once} is too fast, => active is then false and controlling_process does not transfer the message sending to current process to hackney_stream.
Due to this we get an timeout:
2017-05-12 11:21:54 =CRASH REPORT====
crasher:
initial call: couchbeam_changes_stream:init_stream/5
pid: <0.4354.0>
registered_name: []
exception exit: {timeout,[{couchbeam_changes_stream,do_init_stream,1,[{file,"couchbeam_changes_stream.erl"},{line,151}]},{couchbeam_changes_stream,init_stream,5,[{file,"couchbeam_changes_stream.erl"},{line,85}]}]}
ancestors: [couchbeam_changes_sup,couchbeam_sup,<0.1303.0>]
messages: [{ssl,{sslsocket,{gen_tcp,#Port<0.21588>,tls_connection,undefined},<0.4357.0>},<<"HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\nServer: CouchDB/1.6.1 (Erlang OTP/19)\r\nDate: Fri, 12 …

fixed race condition controlling_process

---

src/hackney_connect.erl
src/hackney_pool_handler.erl

There are two issues I ran into, when creating a custom `hackney` pool.
This PR should fix those issues and make it easier for people to implement custom pools.
**Issue:**
The client `pool_handler` is not set, when the pool handler returns `no_socket`.  
**Effect:**
The default `hackney_pool:checkin` is called in stead of the set pool.
This breaks functionality and most likely will cause a direct `gen_server` call to the custom pool pid.
**Issue:**
The `hackney_pool_handler` behaviour is missing the `notify` function.  
**Effect:**
The `notify` function is called after socket usage, which makes the call fail.
Either `notify` should not be used or should be part of the behaviour.
This helps custom pool developers set up the right functions from the start.

Hackney pool handler connect not set when creating new connection

---

src/hackney_pool.erl
test/hackney_pool_tests.erl
test/pool_resource.erl

This mostly resolves https://github.com/benoitc/hackney/issues/420 (and also includes https://github.com/benoitc/hackney/pull/419).
A race condition still exists, between the request timeout occurring till when the cast to `checkout_cancel` is processed.  I suspect it is really unlikely, though fortunately it is detectable so we could choose to do something about it later if this occurs.
A possible improvement would be to when the race occurs we dig around the `client` state element and reclaim the socket back into the pool?

fix deadlock in hackney_pool during request timeout

---

src/hackney_manager.erl
src/hackney_stream.erl
test/hackney_integration_tests.erl
test/hackney_stream_tests.erl

previously we were unlinking a process that started a request each time
a stream were closing or when we were streaming to another process the
response.
This change allows a process to start multiple requests and stream. It
fix it by doing the following:
* only streams and owners are supervised by the manager to track the
socket life
* the stream is responsible of monitoring its target. If the target
process die it exists and the manager clean it
* a process can now have multiple client referenced to it. (which is
done via the addition of track_owner/3 and untrack_owner/3 functions in
the manager).
fix #441

fix owner tracking

---

src/hackney_url.erl

Some servers return redirect codes with Location header like "http://example.com:/
In this situation we should just use standard 80/443 port.

Ignore empty port value on redirect

---

src/hackney_http.erl
src/hackney_response.erl
src/hackney_stream.erl

Ignore non-integer ‘Content-Length’ header.

Handle empty or invalid ‘Content-Length’

---

src/hackney_app.erl
src/hackney_connect.erl
src/hackney_pool.erl

Hackney has been responsible for taking down our site a couple of times, this fixes some of the issues:
1. Hackney's pool runs at high priority despite the fact that docs explicitly tell users not to use this flag. This causes issues when Erlang's scheduler spends too much time interacting with the pool and not enough time doing other things. We've been running without this flag for a couple months, and there's no difference in Hackney's performance. 
1. There was a case clause mismatch that was spamming our logs.
1. Hackney utilizes a metrics module that abstracts between several different metrics providers. This module is dynamically recompiled every time a new connection is created. This recompilation is incredibly expensive, requiring every process in the system to be woken up from …

Hackney performance improvements

---

src/hackney_http.erl

Fix for attempt to fetch failed: {:poorly_formatted_size}. Reference issue: https://github.com/benoitc/hackney/issues/477
` {ok, [Size], []}` was replaced with ` {ok, [Size], _}` here because the third parameter of the output is the list of remaining characters, i.e. the ' ' (ref http://erlang.org/doc/man/io_lib.html#fread-2). By specifying `[]` the code assumed there would be no extra characters in the line (which isn't the case for the web pages in the issue)

Fix for no case clause matching {error,{poorly_formatted_size,"AAE "}}

---

src/hackney.erl
src/hackney_headers_new.erl
src/hackney_manager.erl
src/hackney_response.erl
src/hackney_trace.erl

This is cosmetic, but there are a few instances of nbsp in sources; they were probably added by mistake?
These characters make my Erlide refuse to open these files with an error.

Trivial: Replace no-break space (U+00A0) with ASCII in source files.

---

src/hackney_http.erl

For example, `3 \r\nfoo` currently gets rejected due to the space before CRLF. This change will accept it. This is, as far as I can tell, accepted across browsers, API testing programs (e.g. Insomnia) etc. I'm not really sure whether it's strictly acceptable according to the HTTP spec (a strict reading suggests not, but support is so universal it might be).
There's absolutely no reason for these trailing spaces, but I'm working against an API that's unlikely to change and which ends up including them. Figured I'd fix it for myself at least and see whether this is acceptable for this as well :)

Allow trailing spaces at the end of chunk sizes

---

src/hackney_manager.erl
src/hackney_response.erl

following observations of @obmarg delay the monitoring of the stream process in wait_async_response instead of doing it in monitor_child.
fix #498

fix terminate_async_response

---

src/hackney_ssl.erl

Hi, I was writing an internal monitoring tool and found that I need to access URLs in the form of `https://123.123.123.123/something/` - that is, URLs with HTTPS protocol and numeric IP in the host part. Unfortunately, when I tried issuing such requests I discovered that Hackney doesn't allow this case. (Actually, I was writing in Elixir with HTTPoison, which in turn uses Hackney.)
After some time debugging I discovered that Erlang's ssl application supports requests to IP addresses only if they are presented as four-tuples of ints, not as strings.
I created a quick fix for this which works for me - just before the `ssl:connect` I split the Host string on dots and check if they can be interpreted as an IP address. I'm not sure if it's any good, it's fine if it's not, but then I think it …

Fix accessing HTTPS sites with an IPv4 address

---

src/hackney_url.erl
test/hackney_url_tests.erl

fix parsing query parameters on url without path

---

src/hackney_url.erl

`atom` is not a valid type for the `qs/2` options

Fix invalid type for hackney_ur:qs/2 options

---

src/hackney.erl

Hello!
Current doc is a bit misleading because if you have custom `connect_timeout` when default `checkout_timeout` won't be equal to 8000.

Fix doc for checkout_timeout default

---

src/hackney.app.src
src/hackney_url.erl
test/hackney_url_tests.erl

Related to  #550 
After checking the [RFC ](https://tools.ietf.org/html/rfc3986#section-2.2) section 2.2, Reserved Characters, sub-delims, it seems that url path with '(' ')' characters is valid and should not be encoded.
I would like to do the same for the other characters as well, and do a small refactor that will reflect the RFC.
What do you think?
Cheers

fixed pathencode to support '(' ')' characters

---

doc/hackney.md

Hi.
The documentation for recv_timeout is misleading. It may be confused as timeout for fetching a connection from a connection pool. Can we make a small change to clarify this?

Clarify what recv_timeout means

---

src/hackney_connect.erl
src/hackney_url.erl

some local hostname contains an underscore or other things that are
tolerated by clients like curl. Do the same as curl then and just try to
encode the domain name if it contains some unicode characters.
fix #557

don't try to encode to idna an full ascii name.

---

doc/hackney.md
src/hackney.erl

Hello! 
The spec for `stop_async` seems wrong. The function returns `{ok, client_ref()}` on success not `ok`.
This seems to be confirmed by `examples/test_async_once2.erl`.
```erlang
{ok, Ref} = hackney:stop_async(Ref),
```
Regards,
Radu
P.S. Thanks for providing this library!

correct the spec for stop_async/1

---

doc/hackney_url.md
src/hackney_url.erl

A couple of things that I did here:
* Always use URL in place of url or Url.
* Use `an` article when referring to URL.
* Add link under normalize to pathencode.
* End a few sentences with a full stop, start with a capital letter.

Reformat documentation for hackney_url

---

src/hackney_headers_new.erl
test/hackney_headers_new_test.erl

store/3 creates invalid dict when called with list of Values, causing function_clause in to_list

store/3 creates invalid dict when called with list of Values

---

rebar.config
rebar.lock

To get rid of the `===> ... ssl_verify_fun.app" is missing description entry` warning produced by the latest `rebar3`.

bump ssl_verify_fun to 1.1.5

---

doc/hackney.md
src/hackney.erl

Neither doc nor type spec listed the return type when `with_body` is set to true.

improve docs and type spec

---

.travis.yml
rebar.config
rebar.config.script
src/hackney_ssl.erl

OTP-22.1 (commit `124da8950c`) introduced `assert_role/4` into `:ssl`, which throws an error when `:ssl.connect` is called with the `honor_cipher_order` option defined. The error returned is `{:error, {:option, :server_only, :honor_cipher_order}}`.
With OTP-22.1, a dialyzer warning also appears:
```
129: Invalid type specification for function
hackney_ssl:shutdown/2. The success typing is
( { 'sslsocket',
_,
nonempty_maybe_improper_list()
| {'dtls' | port(), _}
},
'read' | 'read_write' | 'write'
) -> 'ok' | {'error',_}
```
Prior to the above, CI errors began to appear as a result of
cowboy-1.0.4 download failures. Using cowboy-1.1.2 fixes
this.
* remove `honor_cipher_order` option in `connect/4`
* add OTP-22.0 to .travis.yml
* drop OTP-20.2 from .travis.yml (no longer available)
* fix …

Fix error caused by `honor_cipher_order`, CI errors

---

src/hackney_stream.erl

As hackney_manager:handle_error could terminate the request, the request
process should send the response to the owner before calling it.
Right now, with async calls there's a race condition when calling hackney_manager:handle_error before having sent the response (from a {error, Term}) back to the owner. Since hackney_manager:handle_error can kill the caller, and it may have not sent the response yet.
```
$> while true; do echo -e "HTTP/1.1 200 OK\n\n $(date)" | nc -l -p 8081; sleep .1; done
```
```
662> hackney:request(get, "localhost:8081", [], <<>>, [{pool, d}, {stream_to, self()}, async]).
(<0.2645.0>) returned from hackney_stream:parse/1 -> {error,bad_request}
(<0.2645.0>) call hackney_manager:handle_error(
(<0.2645.0>) call hackney_manager:close_request(
(<0.2645.0>) call …
```

Send hackney_response before calling handle_error

---

doc/hackney.md
src/hackney.erl

The previous pull request #555 looks unintentionally reverted by a sort of documentation generation in https://github.com/benoitc/hackney/commit/179c0d69589f0d3e3e35c67d457f0ca117a4cef3 .

Clarify what recv_timeout means again

---

src/hackney_url.erl

The urlencode seems to be broken for a couple of characters. Seems like it's a typo, there a `,` instead of `;`.

Fix urlencode bug

---

src/hackney_response.erl
test/hackney_stream_tests.erl

Due to stream's client not storing the Headers, hackney_response:maybe_close ignores the "Connection: close" response header. This causes that a soon-to-be-closed socket is put back in the pool, potentionally being delivered to other client.
With these changes, hackney_response:maybe_close handles the way hackney_stream stores the connection value

Handle Connection: close response header for streams

---

src/hackney_http.erl
test/hackney_http_tests.erl

Split from https://github.com/benoitc/hackney/pull/604:
In this PR the hparser is updated to consume the actual parsed CRLF newlines at the start of the http message.

Consume leading newlines in http message

---

src/hackney.erl

According to [HTTP/1.1 RFC](https://tools.ietf.org/html/rfc7231#section-7.1.2) the`Location` header value is a single URI-reference. When the reference is relative it should be merged by rules of ["Reference resolution" section of URI RFC](https://tools.ietf.org/html/rfc3986#section-5). From my understanding of that section, no normalization on the relative URI should take place.
Our application generates preview cards for links users submit. We've noticed that the preview links generated for shortened flickr links (i.e `https://flic.kr/p/231oyNG`) are of the wrong picture.
On further investigation I've uncovered that what was happening is:
1. Application uses hackney to request `https://flic.kr/p/231oyNG` with`follow_redirect` set to `true`.
2. Hackney gets the first redirect …

Do not normalize when converting relative redirect URL to absolute

---

README.md

to make it less ambiguous (I thought `timeout` is like total duration of a connection)

Update pool timeout documentation

---

rebar.config
rebar.lock

Any reason `certifi` needs to be pegged to a specific version?

Bump certifi to 2.5.2

---

rebar.config
rebar.lock
src/hackney.app.src
src/hackney_connect.erl
src/hackney_ssl.erl
src/hackney_ssl_certificate.erl

Following your recent changes for OTP 23 support in 66415cf63a, I found some other problems which this PRs proposes fixing.
- broken compilation due to failing `ct_expand` parse transform, fixed in 92c0f4c
- crashing HTTPS requests in OTP 19, fixed in 8eddf7c
- occasional TLS negotiation errors in OTP 20, fixed in 533889d
Cheers,

Fix further issues with TLS/SSL

---

.gitignore
.travis.yml
src/hackney_pool.erl

I got an `xref` analysis error for an unknown function: `ssl:seed` is not documented in Erlang/OTP's doc.s as "maintained" (it's not there at all), so it's most surely been deprecated a good while ago. I leave it to your judgement to reject the PR (keeping current behavior with no more than a little itch to scratch) or accept it (thus embracing the present and the future).

Prevent xref warning for unmaintained Erlang/OTP function

---

src/hackney_connect.erl
src/hackney_pool.erl

Fixes: https://github.com/benoitc/hackney/issues/643
This is similar to PR https://github.com/benoitc/hackney/pull/656, but using `hackney_manager:cancel_request/1` ensures that request state is also erased from process dictionary and deleted from `hackney_manager_refs` ETS table. 
Additionally, this PR includes a memory leak fix (pending client not removed in `hackney_pool:dequeue`) and some code cleanup.

Fixed issue #643 and memory leak in hackney_pool

---

src/hackney.erl

This fixes a problem that caused `hackney:location/1` to return the wrong URL after a redirect if the redirect pointed to a different host.

Update netloc in client state when redirecting

---

src/hackney_response.erl

* fixes #638 
* bug i think appeared in 6ddc33c1
* when streaming the response, we terminate
the parse recursive calls early since
there is no match for {:more, {hparser, ...:on_trailers...}}
case

Handle empty trailers case 

---

README.md
doc/README.md
doc/overview.edoc
src/hackney_pool.erl

While building a custom metrics module for hackney I noticed a few inconsistencies in how some metrics are set up and documented. This PR addresses three of them. I've split them into separate commits to make it easier to review and eventually drop whatever may be irrelevant.
1. Fix the `queue_count` metric documentation and setup. It was being initialized as `queue_counter` in `metrics:new`;
2. Update pool metric docs to match their names. They are currently prefixed with `hackney_pool`, but show up prefixed with `hackney` in the docs;
3. Add documentation for 2 host-based pool metrics: `new_connection` and `reuse_connection`.
Update: Sorry, just noticed 1. is the same change proposed at #583, 2. and 3. are still valid though.

Improve metrics setup and docs

---

src/hackney.app.src
src/hackney_url.erl
test/hackney_url_tests.erl

This change the behaviour of urlencode and pathencode to produce
uppercase hexadecimal following the RFC3986:
The uppercase hexadecimal digits 'A' through 'F' are equivalent to
the lowercase digits 'a' through 'f', respectively. If two URIs
differ only in the case of hexadecimal digits used in percent-encoded
octets, they are equivalent. For consistency, URI producers and
normalizers should use uppercase hexadecimal digits for all percent-
encodings.
breaking change that requires to bump the minor release.

breaking change: produce uppercase hexadecimal in urls

---

.github/workflows/erlang.yml
README.md

Main differences to current CI (Travis):
* using stock `rebar3` instead of "latest" (don't know if this is a hard requirement)
Closes #668.

Implement GitHub Actions

---

src/hackney_connection.erl
src/hackney_ssl.erl

Related to #654
Since it isn't currently possible to merge your custom ssl opts with the default ones it could be a first step to expose the default ones so that the merging can be done client side.

Allow merging of SSL opts

---

src/hackney_pool.erl

This changes remove the intermediate process to checkout a process. When
we reply asynchronously we also check if the proces that will receive
the message is alive.. This should remove any unwanted messages when a
request timeout.
Changes:
* remove intermediate process in hackney_pool:checkout/4
* send async reply only if the requester is alive

make checkout synchronous again

---

src/hackney_connect.erl
test/hackney_pool_tests.erl

This error seems to have disappeared with updates in 1.16.0. This change makes errors related to connection timeouts consistent whether one is using a pool or not. User reported issue here: [benoitc#698](https://github.com/benoitc/hackney/issues/698)

Restore connect timeout error

---

src/hackney_connection.erl

Hi,
I have been using HTTPoison and by extension hackney in a project and found that when making requests to a Unix domain socket sometimes it would be excruciatingly slow. I finally had some time to track it down and discovered that hackney was doing a DNS lookup on the domain socket path which of course would always fail, but sometimes take a long time to do so.
This little patch fixes this problem.
Thankyou so much for making hackney :)
Daniel

Fixed slow unix domain socket requests

---

src/hackney_http.erl
src/hackney_response.erl

I have found some problem with body parsing for chunked encoded messages: https://github.com/benoitc/hackney/issues/690#issuecomment-1321799256
I have understood parsing logic and optimized it. The main point of it to wait necessary portion of data instead of parsing each packet.
My results:
before fix
```
no chunks:
100 requests, total time: 0.663915s
100 requests, total time: 0.677419s
100 requests, total time: 0.678405s
Total data: 1301.7705078125KB, chunk size: 4096, total chunks: 326
100 requests, total time: 0.742954s
100 requests, total time: 0.727678s
100 requests, total time: 0.709221s
Total data: 1301.7705078125KB, chunk size: 40960, total chunks: 33
100 requests, total time: 0.74006s
100 requests, total time: 0.717082s
100 requests, total time: 0.719162s
Total data: …
```

Body parsing optimization

---

rebar.config

Trying to bump `parse_trans` to the latest version.
I am not very familiar with erlang/rebar, please bear with me.

Bump parse_trans to version `3.4.1`

---

src/hackney.app.src

The "Apache License 2.0" has the SPDX ID "Apache-2.0", according to the list at https://spdx.org/licenses/. While the string "Apache 2.0" is fully readable for humans, some tools use these fields to verify what licenses are used, and the tools tend to not be as flexible when reading strings that are interpreted as identifiers.

Use correct SPDX ID for licenses field

---

src/hackney_response.erl

Ensure we don't pass a negative value to recv?
fix #722

recv: if expected size < BufSize fallback to old behaviour

---

src/hackney_http.erl
test/hackney_http_nl_tests.erl

```Although the line terminator for the start-line and header fields is
the sequence CRLF, a recipient MAY recognize a single LF as a line
terminator and ignore any preceding CR.```
I'm running into this issue with an SMS service provider's API where all responses use LF instead of CRLF in the headers.

(feat) Support LF separators since rfc7230-3.5 allows for LF-only

---

README.md
doc/README.md

There's no explicitly stated defaults (that I can find) for `max_connections` and `timeout`.
The README examples, if they are examples of the defaults, say `100` for `max_connections` but then [in `hackney.app.src` it seems to be `50`](https://github.com/benoitc/hackney/blob/01bb4249f595e0aa692db28ef23e70f57ae2d4ed/src/hackney.app.src#L25)? I went with that one but if it is something else, please let me know and happy to update my PR.
Either way it would be helpful to have very clearly stated defaults.

Explicitly state max_connections and timeout defaults in docs

---

src/hackney_url.erl
test/hackney_url_tests.erl

Adds case and test for encoding an asterisk in the path adhering to: https://src.chromium.org/viewvc/chrome/trunk/src/url/url_canon_path.cc#l56
- https://github.com/edgurgel/httpoison/issues/471
- https://github.com/benoitc/hackney/issues/399
- https://github.com/benoitc/hackney/issues/277
- https://github.com/benoitc/hackney/issues/272

Fix partial_pathencode to properly handle asterisk `*`

---

include/hackney.hrl
src/hackney.erl

Hackney handle `HTTP_PROXY` and `HTTPS_PROXY` variables as they define the same thing. In fact (e.g. `curl` documentation) `HTTP_PROXY` should be used only for http requests and `HTTPS_PROXY` should be used only for https requests. This PR fixes that.
Moreover, this PR adds `ALL_PROXY` environment variable handling.

HTTP and HTTPS proxies might differ

---

src/hackney_stream.erl
test/hackney_integration_tests_async_long_headers.erl

The asynchronous node was not handling situation, when the redirect requests were sent chunked.
The PR:
1. Adds `{more, Client2, Rest} ->` case clause read more data if necessary.
2. Allows to configure the continuation from `async_recv/6` function, as by default it was going back to `stream_loop` what is not the case in redirect example.
3. Adds unit test presenting the problem.

Handle chunked responses in the context of redirect requests

---

src/hackney_url.erl
test/hackney_integration_tests.erl
test/hackney_url_tests.erl

fixes #752 [cve-2025-1211](https://github.com/advisories/GHSA-vq52-99r9-h5pw)

fix(hackney_url): parses query string before userinfo

---

.github/workflows/erlang.yml
LICENSE
NEWS.md
README.md
src/hackney.app.src
src/hackney.erl
src/hackney_connection.erl
src/hackney_happy.erl
src/hackney_manager.erl
src/hackney_pool.erl
src/hackney_request.erl
src/hackney_response.erl
src/hackney_ssl.erl
src/hackney_stream.erl
test/hackney_integration_tests.erl
test/hackney_pool_tests.erl
test/hackney_ssl_tests.erl

miscellaneous fixes:
- security: fix basic auth credential exposure vulnerability
- security: add application variable support for insecure_basic_auth
- fix: SSL hostname verification with custom ssl_options and SSL message leak in async streaming
- fix: pool connections not freed on 307 redirects and multiple pool/timer race conditions
- fix: socket leaks, process deadlocks, ETS memory leaks, and infinite gen_server calls
- fix: controlling_process error handling in happy eyeballs and connection pool return
- improvement: update GitHub Actions to ubuntu-22.04 and bump certifi/mimerl dependencies
** Breaking Change **
The new `insecure_basic_auth` application variable defaults to `false` for security.
If your application relies on insecure basic auth over HTTP, you must explicitly set …

Miscellaneous fixes

---

src/hackney.erl
test/hackney_proxy_tests.erl

When proxy environment variables (`http_proxy`, `https_proxy`, etc.) are set to empty strings or whitespace-only values, hackney crashes with a pattern match error in `hackney_url:parse_netloc/2`.
- `export http_proxy=""` causes all hackney requests to fail
- The empty string is passed to URL parsing which expects a valid URL format
- This affects users who clear proxy variables by setting them to empty strings
- Check for empty strings in `do_get_proxy_env/1` before attempting to parse
- Strip whitespace from proxy URLs and treat whitespace-only values as empty
- Skip to the next proxy variable in the list when empty values are found

fix: handle empty proxy environment variables

---

src/hackney_connection.erl

Hello!
If `server_name_indication` is passed, then the server provides us the appropriate certificate. So we need to match the passed SNI value with the certificate, not the connect host.

Fix default ssl options in presence of SNI

---

src/hackney_pool.erl

This PR fixes the performance regression reported in #775 where `checkout_timeout` errors occur under load.
The timeout in `cancel_timer/2` was changed from 0ms to 100ms, causing performance issues when the function is called multiple times on the same timer during error scenarios.
Restore the original 0ms timeout to eliminate the delay while maintaining proper timer cleanup.
Fixes #775

Fix pool connection handling regression under load
